version: '3'
services:
  client:
    image: node:latest
    ports: 
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm start"
  api:
    image: node:latest
    working_dir: /code
    ports:
      - 3000:3000
    environment:
    - PGUSER=posts_user
    - PGPASSWORD=posts123
    - PGHOST=db
    - PGDATABASE=db
    - PGPORT=5432
    depends_on:
     - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=posts_user
      - POSTGRES_PASSWORD=posts123
volumes:
  dbdata:
